site_name: Noversia Platform
theme:
  name: material
  language: fr
nav:
  - Accueil: docs/index.md
  - Produit:
      - Marchands: docs/02-product/merchants.md
      - Catégorisation: docs/02-product/categorization.md
  - Architecture:
      - Module Transactions: docs/05-architecture/transactions-module.md
  - Données:
      - Modèle initial: docs/07-data-model/data-model-overview.md
  - API:
      - Standards API: docs/08-api/api-standards.md
  - Roadmap:
      - Roadmap: docs/13-roadmap/roadmap.md
