site_name: Noversia Platform
theme:
  name: material
  language: fr
nav:
  - Accueil: docs/index.md
  - Produit:
      - MVP: docs/02-product/mvp.md
      - Import CSV: docs/02-product/csv-import.md
  - Architecture:
      - Vue globale: docs/05-architecture/overview.md
      - Backend Go: docs/05-architecture/backend-go.md
  - Données:
      - Modèle initial: docs/07-data-model/data-model-overview.md
  - API:
      - Standards API: docs/08-api/api-standards.md
  - Roadmap:
      - Roadmap: docs/13-roadmap/roadmap.md
